<?php

namespace TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findAllByDueDate($user){
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT t FROM TaskBundle:Task t
            WHERE t.taskOwner = :user
            ORDER BY t.dueDate ASC')
            ->setParameter('user', $user);
        return $query->getResult();
    }
}
