<?php

namespace TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersTaskRepository extends EntityRepository
{
}
